API_URL = 'https://api.todoist.com/rest/v2/tasks'

FILTER_INIT_CHAR = '?'
FILTER_CONTINUE_CHAR = '&'
FILTER_ASING_CHAR = '='

PROJECT_ID = 'project_id'
FILTER = 'filter'

OVERDUE_AND_TODAY_AND_DAY_AFTER = '(today|overdue|+2days)'
PROJECT_PLACEHOLDER = '<project-id>'

FILTER_PROJECT_ID = FILTER_INIT_CHAR + PROJECT_ID + FILTER_ASING_CHAR + PROJECT_PLACEHOLDER
FILTER_BY_DUE = FILTER_CONTINUE_CHAR + FILTER + FILTER_ASING_CHAR + OVERDUE_AND_TODAY_AND_DAY_AFTER

HEADER_AUTH = 'Authorization'
HEADER_BEARER = 'Bearer '

HTTP_GET_METHOD = 'GET'