API_URL = 'https://apidatos.ree.es/es/datos/mercados/precios-mercados-tiempo-real'

FILTER_INIT_CHAR = '?'
FILTER_CONTINUE_CHAR = '&'
FILTER_ASING_CHAR = '='

START_DATE = 'start_date'
END_DATE = 'end_date'

FILTER_START_DATE_TODAY = FILTER_INIT_CHAR + START_DATE + FILTER_ASING_CHAR
FILTER_END_DATE_TODAY = FILTER_CONTINUE_CHAR + END_DATE + FILTER_ASING_CHAR
FILTER_TIME_TRUNC_HOUR = FILTER_CONTINUE_CHAR + 'time_trunc=hour'


HTTP_GET_METHOD = 'GET'